### PR TITLE
Macro11 v0.7.2

### PR DESCRIPTION
**Pull request by Rhialto**
As mentioned by @khandy21yo here is an update of macro11. It contains the full history of changes. If wanted you can "squash" this whole history down to a single commit when merging. I don't know what policy you want to apply to this repo, I just thought I'd mention it.

### CODE REVIEW

**Comment by pkoning2** [comment]
Thanks Olaf.  I don't see a problem with all the separate commits, let's see if others have a different view.

Is your intent to keep this copy somewhat up to date?  I was thinking for cases like this one, where there is a "primary" copy that's kept elsewhere, to add a README file that has a link to that primary site.  Then it can also say that the copy here is a snapshot that is periodically synchronized, or that it's a snapshot for which that is not done, depending on what's actually the practice.

**Comment by unixwizard107** [comment]
Separate commits work for me.  This all looks great.

WRT to primary - I don't care where it is, but I do care that we are explicit in the top-level readme noting the relationship of a (this) specific repository to the other and solid pointer to when the last time each was in sync.    Not trying to make the lock step, but rather add the flexibility for them to diverge as needed, but recognize that fact.

My >>hope<< is that simh can keep something that is pretty close to the top of the tree but known to work for the primary PDP-11 systems that people are running on the simulator.  I would expect someone like Olaf or Paul who might discover a discontinuity when trying to do something like build RSX or RSTS and having to repair the code tool.  The question then comes how to bring that fix/feature back into the fold without breaking anything from before.

**Comment by Rhialto** [comment]
I'm not sure what happens if somebody modifies some file in the macro11 subdirectory, and then another "git subtree pull ..." is done. Maybe it just manages to merge things, maybe it fails. I never tried it...

As for a note in the README.md; I'll add a one-line remark (if it fits) with a reference to the source location and that it was synced to to the 0.7.2. release (and add that to this merge request).

**Comment by pkoning2** [comment]
My thinking for having a pointer to the primary copy is to tell people not to make fixes here, but instead submit them to the primary codebase.  For example, I have a set of fixes waiting to be delivered; now that I know there is a different primary macro11 repository I'll sync with that and deliver there, rather than here.

**Comment by unixwizard107** [comment]
Paul says: "_My thinking for having a pointer to the primary copy is to tell people not to make fixes here, but instead submit them to the primary codebase_" - exactly.  I think we should document Open-Simh/simhtools/.../macro11 as subservient to Olaf's repository - _i.e._ it is a pointer to his.   We keep a cache of a version that is known to work with the systems that simh/pdp11 simulator primary supports.

**Comment by Rhialto** [comment]
On Wed 08 Jun 2022 at 14:05:38 -0700, Paul Koning wrote:
> For example, I have a set of fixes waiting to be delivered; now that I know there is a different primary macro11 repository I'll sync with that and deliver there, rather than here.

Ah yes, if your fixes were based on the version that was in the simtools
repo, then they might have been independently discovered in the mean
time by one of the bug reporters or me.
Nevertheless I'm curious what they are, especially if any are still left
over: missing features, missing syntax, not detecting bad input (there
was a fix for such a thing recently after the release), whatever.

**Pull request merged**
