### PR TITLE
SIMTOOLS:  Logical-to-physical converter for single-sided floppy images

### PR DESCRIPTION
**Pull request by al20878**
Prompted by discussion on simh@groups.io:
https://groups.io/g/simh/topic/need_some_help_with_rt_11/108655724

Donating this converter in hope that it's going to be useful

### CODE REVIEW

**Comment by al20878** [comment]
I checked the L2P algorithm for i==2, but it looks like it's incorrect for arbitrary T, S, and i values.  I need to clarify that and will update the pull request, accordingly...

**Comment by al20878** [comment]
Is there a problem with accepting this piece of code?

**Comment by pkoning2** [comment]
No, I just missed the notice.  Fixed.

**Comment by al20878** [comment]
Thanks for that.  I have since submitted two more PRs and maybe they have
been missed as well.  Please take a look.

**Pull request merged**
